set DIR Ex
set SYMLINK gx
set SOCKET cx
set PIPE cx
set EXE Dx
set BLOCKSP xx
set CHARSP xx
set EXESUID Dx
set EXEGUID Dx
set DIRSTICKY Ex
set DIRWOSTICKY Ex
set -x LSCOLORS "$DIR$SYMLINK$SOCKET$PIPE$EXE$BLOCKSP$CHARSP$EXESUID$EXEGUID$DIRSTICKY$DIRWOSTICKY"